[versions]
agp = "9.0.0"
coreSplashscreen = "1.2.0"
facebookLogin = "18.1.3"
firebaseBom = "34.8.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
lottie = "6.7.1"
material = "1.13.0"
activity = "1.12.3"
constraintlayout = "2.2.1"
fragment = "1.8.9"
navigationFragment = "2.9.7"
navigationUi = "2.9.7"
firebaseAuth = "24.0.1"
playServicesAuth = "21.0.0"
retrofit = "2.9.0"
rxjava = "3.1.6"
rxandroid = "3.0.2"
glide = "4.16.0"

[libraries]
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
facebook-login = { module = "com.facebook.android:facebook-login", version.ref = "facebookLogin" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
fragment = { group = "androidx.fragment", name = "fragment", version.ref = "fragment" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuth" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
adapter-rxjava3 = { module = "com.squareup.retrofit2:adapter-rxjava3", version.ref = "retrofit" }
rxjava = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava" }
rxandroid = { module = "io.reactivex.rxjava3:rxandroid", version.ref = "rxandroid" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
navigation-safeargs = { id = "androidx.navigation.safeargs", version.ref = "navigationFragment" }
